# Generated by Django 4.1.2 on 2023-06-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='imagen',
            field=models.ImageField(null=True, upload_to='artistas'),
        ),
    ]
