# Generated by Django 4.1.2 on 2023-07-07 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_tipo_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
    ]
